### ISSUE TITLE
Can't install in Raspberry Pi

### ISSUE THREAD

**Issue by thewinger** [stefantalpalaru/deluge-default-trackers#19]
I have created the egg in the raspberry pi where deluge is installed, copied the .egg to the plugins folder and when I start Deluge this is the message that shows:

[ERROR   ] 10:33:07 pluginmanagerbase:146 Unable to instantiate plugin!
[ERROR   ] 10:33:07 pluginmanagerbase:147 No module named requests
Traceback (most recent call last):
   File "/usr/lib/python2.7/dist-packages/deluge/pluginmanagerbase.py", line
     instance = cls(plugin_name.replace("-", "_"))
   File "build/bdist.linux-armv7l/egg/defaulttrackers/__init__.py", line 45,
     from core import Core as _plugin_cls
   File "build/bdist.linux-armv7l/egg/defaulttrackers/core.py", line 44, in
 ImportError: No module named requests

Any idea what is happening?

**Comment by thewinger** [comment]
My bad!
Installed python's requests module.
