### ISSUE TITLE
Update for Deluge v2

### ISSUE THREAD

**Issue by theg00s3** [stefantalpalaru/deluge-default-trackers#26]
Will this be updated for deluge v2?

**Comment by theg00s3** [comment]
I've made an attempt on [my fork](https://github.com/theg00s3/deluge-default-trackers), but there's a weird issue I can't solve. The plugin appears in Deluge's plugin list, but the enabled box can't be ticked. The error is the log is below.

````13:08:43 [ERROR ][deluge.pluginmanagerbase :154 ] Unable to instantiate plugin 'DefaultTrackers' from '/home/nikila/.config/deluge/plugins/DefaultTrackers-2.1-py3.6.egg'!
13:08:43 [ERROR ][deluge.pluginmanagerbase :1343] No module named 'deluge_defaulttrackers'
Traceback (most recent call last):
File "/usr/lib/python3/dist-packages/deluge/pluginmanagerbase.py", line 147, in enable_plugin
cls = egg.load_entry_point(self.entry_name, name)
File "/usr/lib/python3/dist-packages/pkg_resources/__init__.py", line 2693, in load_entry_point
return ep.load()
File "/usr/lib/python3/dist-packages/pkg_resources/__init__.py", line 2324, in load
return self.resolve()
File "/usr/lib/python3/dist-packages/pkg_resources/__init__.py", line 2330, in resolve
module = __import__(self.module_name, fromlist=['__name__'], level=0)
ModuleNotFoundError: No module named 'deluge_defaulttrackers'````

**Comment by stefantalpalaru** [comment]
Plugin updated.
