### ISSUE TITLE
Plugin not showing up in Ubuntu 22.04.1

### ISSUE THREAD

**Issue by luigi-bar** [stefantalpalaru/deluge-default-trackers#43]
Hi,
   i am using the following:
```

>>> lsb_release -a ; python3 --version ; deluge --version
LSB Version:	core-11.1.0ubuntu4-noarch:printing-11.1.0ubuntu4-noarch:security-11.1.0ubuntu4-noarch
Distributor ID:	Ubuntu
Description:	Ubuntu 22.04.1 LTS
Release:	22.04
Codename:	jammy

Python 3.10.6

deluge 2.0.3
libtorrent: 2.0.5.0
Python: 3.10.6
OS: Linux Ubuntu 22.04 Jammy Jellyfish
```

after cloning the repo and building/installing  with `python3 setup.py bdist_egg`  and restarting deluge, the plugin does not appear in the plugins list. It is present in .config/deluge/plugins

 I get a number of errors related to disk (see below) but maybe it is unrelated.
Any help would be appreciated, thanks!
Luigi

```
13:17:37 [CRITICAL][twisted                           :147 ] Unhandled Error
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/deluge/ui/gtk3/gtkui.py", line 246, in start
    reactor.run()
  File "/usr/lib/python3/dist-packages/twisted/internet/_glibbase.py", line 277, in run
    self._run()
  File "/usr/lib/python3/dist-packages/gi/overrides/Gtk.py", line 1689, in main
    return _Gtk_main(*args, **kwargs)
  File "/usr/lib/python3/dist-packages/twisted/internet/_glibbase.py", line 308, in _simulate
    self.runUntilCurrent()
--- <exception caught here> ---
  File "/usr/lib/python3/dist-packages/twisted/internet/base.py", line 991, in runUntilCurrent
    call.func(*call.args, **call.kw)
  File "/usr/lib/python3/dist-packages/deluge/core/core.py", line 345, in _on_alert_session_stats
    self._update_session_cache_hit_ratio()
  File "/usr/lib/python3/dist-packages/deluge/core/core.py", line 361, in _update_session_cache_hit_ratio
    self.session_status['disk.num_blocks_cache_hits'] / blocks_read
builtins.KeyError: 'disk.num_blocks_cache_hits'

```

**Comment by stefantalpalaru** [comment]
Check the plugin file name with `ls -l ~/.config/deluge/plugins`. Does it end in `py3.10.egg`?

Also, do you get any error on the terminal when opening Deluge preferences?

**Comment by luigi-bar** [comment]
Hi,
no errors... but the file is named: 

```
ls -l ~/.config/deluge/plugins
total 44
-rw-rw-r-- 1 luigi luigi 33796 feb 11 12:16 DefaultTrackers-0.4-py3.9.egg
```

after renaming to ".....py3.10.egg" it worked .

Thanks!
